/** ISO 639-1 languages commonly encountered in book cataloguing */
export const LANGUAGES = [
  { value: "en", label: "English" },
  { value: "es", label: "Spanish" },
  { value: "fr", label: "French" },
  { value: "de", label: "German" },
  { value: "it", label: "Italian" },
  { value: "pt", label: "Portuguese" },
  { value: "ru", label: "Russian" },
  { value: "ja", label: "Japanese" },
  { value: "zh", label: "Chinese" },
  { value: "ar", label: "Arabic" },
  { value: "ko", label: "Korean" },
  { value: "nl", label: "Dutch" },
  { value: "sv", label: "Swedish" },
  { value: "pl", label: "Polish" },
  { value: "cs", label: "Czech" },
  { value: "da", label: "Danish" },
  { value: "fi", label: "Finnish" },
  { value: "no", label: "Norwegian" },
  { value: "hu", label: "Hungarian" },
  { value: "ro", label: "Romanian" },
  { value: "tr", label: "Turkish" },
  { value: "el", label: "Greek" },
  { value: "la", label: "Latin" },
  { value: "he", label: "Hebrew" },
  { value: "hi", label: "Hindi" },
  { value: "uk", label: "Ukrainian" },
  { value: "ca", label: "Catalan" },
  { value: "sr", label: "Serbian" },
  { value: "hr", label: "Croatian" },
  { value: "bg", label: "Bulgarian" },
  { value: "fa", label: "Persian" },
  { value: "ga", label: "Irish" },
  { value: "cy", label: "Welsh" },
  { value: "grc", label: "Ancient Greek" },
  { value: "sa", label: "Sanskrit" },
] as const;
