/**
 * English names of language codes, fixed in the code. Server and browser
 * read the same table, so a name never depends on the runtime: Chrome's
 * Intl knows no "grc" or "ota", Node does, and a page rendered on one and
 * hydrated on the other would disagree. Generated once from Node's Intl
 * (every two-letter code it names, and the historical three-letter codes a
 * library meets); add a code here when a record needs it.
 */
export const LANGUAGE_NAMES: Record<string, string> = {
  aa: "Afar",
  ab: "Abkhazian",
  ae: "Avestan",
  af: "Afrikaans",
  ak: "Akan",
  akk: "Akkadian",
  am: "Amharic",
  an: "Aragonese",
  ang: "Old English",
  ar: "Arabic",
  arc: "Aramaic",
  as: "Assamese",
  ast: "Asturian",
  av: "Avaric",
  ay: "Aymara",
  az: "Azerbaijani",
  ba: "Bashkir",
  be: "Belarusian",
  bg: "Bulgarian",
  bh: "Bhojpuri",
  bi: "Bislama",
  bm: "Bambara",
  bn: "Bangla",
  bo: "Tibetan",
  br: "Breton",
  bs: "Bosnian",
  ca: "Catalan",
  ce: "Chechen",
  ch: "Chamorro",
  chu: "Church Slavic",
  co: "Corsican",
  cop: "Coptic",
  cr: "Cree",
  cs: "Czech",
  cu: "Church Slavic",
  cv: "Chuvash",
  cy: "Welsh",
  da: "Danish",
  de: "German",
  dsb: "Lower Sorbian",
  dv: "Divehi",
  dz: "Dzongkha",
  ee: "Ewe",
  egy: "Ancient Egyptian",
  el: "Greek",
  en: "English",
  enm: "Middle English",
  eo: "Esperanto",
  es: "Spanish",
  et: "Estonian",
  eu: "Basque",
  fa: "Persian",
  ff: "Fula",
  fi: "Finnish",
  fil: "Filipino",
  fj: "Fijian",
  fo: "Faroese",
  fr: "French",
  frm: "Middle French",
  fro: "Old French",
  frr: "Northern Frisian",
  fur: "Friulian",
  fy: "Western Frisian",
  ga: "Irish",
  gd: "Scottish Gaelic",
  gl: "Galician",
  gmh: "Middle High German",
  gn: "Guarani",
  goh: "Old High German",
  got: "Gothic",
  grc: "Ancient Greek",
  gsw: "Swiss German",
  gu: "Gujarati",
  gv: "Manx",
  ha: "Hausa",
  haw: "Hawaiian",
  he: "Hebrew",
  hi: "Hindi",
  ho: "Hiri Motu",
  hr: "Croatian",
  hsb: "Upper Sorbian",
  ht: "Haitian Creole",
  hu: "Hungarian",
  hy: "Armenian",
  hz: "Herero",
  ia: "Interlingua",
  id: "Indonesian",
  ie: "Interlingue",
  ig: "Igbo",
  ii: "Sichuan Yi",
  ik: "Inupiaq",
  in: "Indonesian",
  io: "Ido",
  is: "Icelandic",
  it: "Italian",
  iu: "Inuktitut",
  iw: "Hebrew",
  ja: "Japanese",
  ji: "Yiddish",
  jv: "Javanese",
  jw: "Javanese",
  ka: "Georgian",
  kg: "Kongo",
  ki: "Kikuyu",
  kj: "Kuanyama",
  kk: "Kazakh",
  kl: "Kalaallisut",
  km: "Khmer",
  kn: "Kannada",
  ko: "Korean",
  kr: "Kanuri",
  ks: "Kashmiri",
  ku: "Kurdish",
  kv: "Komi",
  kw: "Cornish",
  ky: "Kyrgyz",
  la: "Latin",
  lad: "Ladino",
  lb: "Luxembourgish",
  lg: "Ganda",
  li: "Limburgish",
  ln: "Lingala",
  lo: "Lao",
  lt: "Lithuanian",
  lu: "Luba-Katanga",
  lv: "Latvian",
  mg: "Malagasy",
  mh: "Marshallese",
  mi: "Māori",
  mk: "Macedonian",
  ml: "Malayalam",
  mn: "Mongolian",
  mo: "Romanian",
  mr: "Marathi",
  ms: "Malay",
  mt: "Maltese",
  mul: "Multiple languages",
  my: "Burmese",
  na: "Nauru",
  nap: "Neapolitan",
  nb: "Norwegian Bokmål",
  nd: "North Ndebele",
  nds: "Low German",
  ne: "Nepali",
  ng: "Ndonga",
  nl: "Dutch",
  nn: "Norwegian Nynorsk",
  no: "Norwegian",
  non: "Old Norse",
  nr: "South Ndebele",
  nv: "Navajo",
  ny: "Nyanja",
  oc: "Occitan",
  oj: "Ojibwa",
  om: "Oromo",
  or: "Odia",
  os: "Ossetic",
  ota: "Ottoman Turkish",
  pa: "Punjabi",
  peo: "Old Persian",
  pi: "Pali",
  pl: "Polish",
  pli: "Pali",
  pro: "Old Provençal",
  ps: "Pashto",
  pt: "Portuguese",
  qu: "Quechua",
  rm: "Romansh",
  rn: "Rundi",
  ro: "Romanian",
  ru: "Russian",
  rup: "Aromanian",
  rw: "Kinyarwanda",
  sa: "Sanskrit",
  sc: "Sardinian",
  scn: "Sicilian",
  sd: "Sindhi",
  se: "Northern Sami",
  sg: "Sango",
  sga: "Old Irish",
  sh: "Serbian (Latin)",
  si: "Sinhala",
  sk: "Slovak",
  sl: "Slovenian",
  sm: "Samoan",
  sn: "Shona",
  so: "Somali",
  sq: "Albanian",
  sr: "Serbian",
  ss: "Swati",
  st: "Southern Sotho",
  su: "Sundanese",
  sux: "Sumerian",
  sv: "Swedish",
  sw: "Swahili",
  syc: "Classical Syriac",
  ta: "Tamil",
  te: "Telugu",
  tg: "Tajik",
  th: "Thai",
  ti: "Tigrinya",
  tk: "Turkmen",
  tl: "Filipino",
  tn: "Tswana",
  to: "Tongan",
  tr: "Turkish",
  ts: "Tsonga",
  tt: "Tatar",
  tw: "Akan",
  ty: "Tahitian",
  ug: "Uyghur",
  uk: "Ukrainian",
  ur: "Urdu",
  uz: "Uzbek",
  ve: "Venda",
  vec: "Venetian",
  vi: "Vietnamese",
  vo: "Volapük",
  wa: "Walloon",
  wo: "Wolof",
  xh: "Xhosa",
  yi: "Yiddish",
  yo: "Yoruba",
  yue: "Cantonese",
  za: "Zhuang",
  zh: "Chinese",
  zu: "Zulu",
  zxx: "No linguistic content",
};
