import type { Outlet } from "./outlets";

/**
 * The outlet registry's seed (SLN-468), applied by `scripts/enrichment/evidence.ts
 * --outlets --apply` only after Pablo approves the outlets, weights and
 * policies. A new version replaces the registry: outlets that leave it are
 * retired, never deleted. To undo a version, apply the previous one.
 *
 * `fetch` only where the outlet's terms were read and do not forbid automated
 * access; otherwise `snippet_only` (the research agent keeps a search
 * snippet) until the terms are read. robots.txt still decides every fetch.
 */
export const OUTLET_SEED_VERSION = 1;

const CHECKED = "2026-10-07";

type Seed = Omit<Outlet, "status" | "syndicationGroup" | "termsUrl" | "termsCheckedOn" | "termsNote"> &
  Partial<Pick<Outlet, "syndicationGroup" | "termsUrl" | "termsCheckedOn" | "termsNote">>;

const outlet = (o: Seed): Outlet => ({ syndicationGroup: null, termsUrl: null, termsCheckedOn: null, termsNote: null, status: "active", ...o });

export const OUTLET_SEED: readonly Outlet[] = [
  // The outlets SLN-460 names (pipeline step 3)
  outlet({
    key: "nyrb",
    name: "The New York Review of Books",
    domains: ["nybooks.com"],
    kind: "review",
    language: "en",
    weight: 0.95,
    fetchPolicy: "fetch",
    termsUrl: "https://www.nybooks.com/terms/",
    termsCheckedOn: CHECKED,
    termsNote: "Copying for noncommercial personal use is allowed; no clause on automated access. robots.txt allows reviews.",
  }),
  outlet({
    key: "lrb",
    name: "London Review of Books",
    domains: ["lrb.co.uk"],
    kind: "review",
    language: "en",
    weight: 0.95,
    fetchPolicy: "fetch",
    termsUrl: "https://www.lrb.co.uk/pages/terms/terms-conditions",
    termsCheckedOn: CHECKED,
    termsNote: "Download and storage for personal, private, non-commercial use is allowed. Subscriber-only pieces answer as a paywall and are not fetched.",
  }),
  outlet({
    key: "tls",
    name: "The Times Literary Supplement",
    domains: ["the-tls.com", "the-tls.co.uk"],
    kind: "review",
    language: "en",
    weight: 0.95,
    fetchPolicy: "snippet_only",
    termsNote: "robots.txt disallows every crawler it does not name, so pages are never fetched.",
  }),
  outlet({
    key: "guardian",
    name: "The Guardian",
    domains: ["theguardian.com"],
    kind: "press",
    language: "en",
    weight: 0.8,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are.",
  }),
  outlet({
    key: "nyt",
    name: "The New York Times",
    domains: ["nytimes.com"],
    kind: "press",
    language: "en",
    weight: 0.85,
    fetchPolicy: "snippet_only",
    termsUrl: "https://help.nytimes.com/hc/en-us/articles/115014893428-Terms-of-Service",
    termsNote: "The terms forbid robots, scrapers and automated tools.",
  }),
  outlet({
    key: "new-yorker",
    name: "The New Yorker",
    domains: ["newyorker.com"],
    kind: "press",
    language: "en",
    weight: 0.9,
    fetchPolicy: "snippet_only",
    termsNote: "Terms (Condé Nast user agreement) not read yet: snippets only until they are.",
  }),
  outlet({
    key: "bookforum",
    name: "Bookforum",
    domains: ["bookforum.com"],
    kind: "review",
    language: "en",
    weight: 0.85,
    fetchPolicy: "fetch",
    termsUrl: "https://www.bookforum.com/terms",
    termsCheckedOn: CHECKED,
    termsNote: "The terms cover subscriptions and delivery; no clause on automated access. No robots.txt (no rules).",
  }),
  outlet({
    key: "words-without-borders",
    name: "Words Without Borders",
    domains: ["wordswithoutborders.org"],
    kind: "review",
    language: "en",
    weight: 0.8,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are. robots.txt allows everything.",
  }),
  outlet({
    key: "asymptote",
    name: "Asymptote",
    domains: ["asymptotejournal.com"],
    kind: "review",
    language: "en",
    weight: 0.75,
    fetchPolicy: "snippet_only",
    termsNote: "No terms page found; rights stay with authors and translators. Snippets only until Pablo decides.",
  }),
  // Press in the original languages: French, German, Russian, Portuguese, Spanish
  outlet({
    key: "le-monde",
    name: "Le Monde",
    domains: ["lemonde.fr"],
    kind: "press",
    language: "fr",
    weight: 0.8,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are.",
  }),
  outlet({
    key: "en-attendant-nadeau",
    name: "En attendant Nadeau",
    domains: ["en-attendant-nadeau.fr"],
    kind: "review",
    language: "fr",
    weight: 0.85,
    fetchPolicy: "fetch",
    termsUrl: "https://www.en-attendant-nadeau.fr/mentions-legales/",
    termsCheckedOn: CHECKED,
    termsNote: "Reproduction and distribution need consent; quotation with attribution is allowed. No clause on automated access; the copy stays private.",
  }),
  outlet({
    key: "liberation",
    name: "Libération",
    domains: ["liberation.fr"],
    kind: "press",
    language: "fr",
    weight: 0.7,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are.",
  }),
  outlet({
    key: "faz",
    name: "Frankfurter Allgemeine Zeitung",
    domains: ["faz.net"],
    kind: "press",
    language: "de",
    weight: 0.8,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are.",
  }),
  outlet({
    key: "sueddeutsche",
    name: "Süddeutsche Zeitung",
    domains: ["sueddeutsche.de"],
    kind: "press",
    language: "de",
    weight: 0.75,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are.",
  }),
  outlet({
    key: "zeit",
    name: "Die Zeit",
    domains: ["zeit.de"],
    kind: "press",
    language: "de",
    weight: 0.8,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are.",
  }),
  outlet({
    key: "perlentaucher",
    name: "Perlentaucher",
    domains: ["perlentaucher.de"],
    kind: "review",
    language: "de",
    weight: 0.5,
    fetchPolicy: "fetch",
    termsUrl: "https://www.perlentaucher.de/impressum-kontakt/nutzerbestimmungen.html",
    termsCheckedOn: CHECKED,
    termsNote: "The user terms cover comments only. A digest of other papers' reviews: never independent of the paper it sums up.",
  }),
  outlet({
    key: "gorky",
    name: "Gorky",
    domains: ["gorky.media"],
    kind: "review",
    language: "ru",
    weight: 0.8,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are. robots.txt allows everything.",
  }),
  outlet({
    key: "colta",
    name: "Colta",
    domains: ["colta.ru"],
    kind: "review",
    language: "ru",
    weight: 0.65,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are. robots.txt allows everything.",
  }),
  outlet({
    key: "folha",
    name: "Folha de S.Paulo",
    domains: ["folha.uol.com.br"],
    kind: "press",
    language: "pt",
    weight: 0.75,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are.",
  }),
  outlet({
    key: "publico",
    name: "Público",
    domains: ["publico.pt"],
    kind: "press",
    language: "pt",
    weight: 0.7,
    fetchPolicy: "snippet_only",
    termsNote: "Its robots.txt answered 403 (a bot block): snippets only.",
  }),
  outlet({
    key: "quatro-cinco-um",
    name: "Quatro Cinco Um",
    domains: ["quatrocincoum.com.br"],
    kind: "review",
    language: "pt",
    weight: 0.8,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are.",
  }),
  outlet({
    key: "el-pais",
    name: "El País",
    domains: ["elpais.com"],
    kind: "press",
    language: "es",
    weight: 0.75,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are.",
  }),
  outlet({
    key: "letras-libres",
    name: "Letras Libres",
    domains: ["letraslibres.com"],
    kind: "review",
    language: "es",
    weight: 0.8,
    fetchPolicy: "snippet_only",
    termsNote: "Terms not read yet: snippets only until they are. No robots.txt.",
  }),
  outlet({
    key: "el-cultural",
    name: "El Cultural",
    domains: ["elcultural.com"],
    kind: "review",
    language: "es",
    weight: 0.7,
    fetchPolicy: "snippet_only",
    termsNote: "It redirects to El Español, which is not in the registry: snippets only.",
  }),
  // Academic, open access
  outlet({
    key: "openedition-journals",
    name: "OpenEdition Journals",
    domains: ["journals.openedition.org"],
    kind: "academic",
    language: null,
    weight: 0.75,
    fetchPolicy: "fetch",
    termsUrl: "https://journals.openedition.org/",
    termsCheckedOn: CHECKED,
    termsNote: "Articles are mostly under Creative Commons BY-NC-ND, which allows non-commercial copies. robots.txt allows articles.",
  }),
  outlet({
    key: "erudit",
    name: "Érudit",
    domains: ["erudit.org"],
    kind: "academic",
    language: null,
    weight: 0.7,
    fetchPolicy: "snippet_only",
    termsNote: "Licence not read yet: snippets only until it is. robots.txt asks for 10 s between requests.",
  }),
  outlet({
    key: "scielo",
    name: "SciELO",
    domains: ["scielo.org"],
    kind: "academic",
    language: null,
    weight: 0.65,
    fetchPolicy: "snippet_only",
    termsNote: "robots.txt disallows every crawler it does not name, so pages are never fetched.",
  }),
];
